Started updating documentation for rotary encoder. Issue 98
oss-slu/Pi4Micronaut pull request #100
Opened 2023-10-25 19:40 UTC by joefol

Need to finish updating all of the fields in the adoc.

2023-11-02 22:04 UTC, ruthvikm requested changes

2023-11-02 22:04 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/components/inputComponents/rotaryEncoder.adoc
> +===== Functionality
Try to identify the units of the value which is returned it might be radians but make sure and mention it here

2023-11-02 22:04 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/components/inputComponents/rotaryEncoder.adoc
> +
Assembly instructions are missing

2023-11-02 22:25 UTC, SwindleA commented on micronautpi4j-utils/src/docs/asciidoc/components/inputComponents/rotaryEncoder.adoc
> +knob counterclockwise will decrease the value returned.
Dumb question: can the shaft continuously rotate, or is there a max amount that you can rotate it?

2023-11-03 20:08 UTC, SwindleA approved these changes
Looks good

2023-11-03 21:16 UTC, ruthvikm approved these changes

2023-11-03 21:16 UTC, merged