RFID documentation
oss-slu/Pi4Micronaut pull request #101
Opened 2023-10-27 18:07 UTC by SwindleA

Still need to test the circuit, add a circuit diagram, and outline how to test the circuit.

2023-11-02 14:38 UTC, ruthvikm requested changes

2023-11-02 14:38 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/components/inputComponents/rfidScanner.adoc
> +
These are the only components which you have used while building this circuit?

2023-11-02 14:38 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/components/inputComponents/rfidScanner.adoc
> +image::https://docs.sunfounder.com/projects/davinci-kit/en/latest/_images/image232.png[]
You the image which you uploaded in our repository.
"micronautpi4j-utils/src/docs/asciidoc/images/rfid_circuit.png"

2023-11-02 14:38 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/components/inputComponents/rfidScanner.adoc
> +
Missing Assembly instructions section

2023-11-02 14:38 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/components/inputComponents/rfidScanner.adoc
> +
Missing Functionalities section

2023-11-02 14:38 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/components/inputComponents/rfidScanner.adoc
> +
Missing troubleshooting section

2023-11-02 14:42 UTC, ruthvikm requested changes

2023-11-02 14:42 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/components/inputComponents/slideSwitch.adoc
Add the missing sections to this as well.

2023-11-02 21:43 UTC, SwindleA commented on micronautpi4j-utils/src/docs/asciidoc/components/inputComponents/rfidScanner.adoc
> +
Yes. The LCD display that was connected yesterday was for the example program. These are the only components needed for the RFID scanner.

2023-11-02 21:45 UTC, SwindleA commented on micronautpi4j-utils/src/docs/asciidoc/components/inputComponents/rfidScanner.adoc
> +image::https://docs.sunfounder.com/projects/davinci-kit/en/latest/_images/image232.png[]
So, currently the images that I include from the repository are not showing when the docs are built. The images that are included from a website are. This should probably be a separate issue to fix.

2023-11-03 00:52 UTC, ruthvikm requested changes
Slide switch looks good

2023-11-03 00:52 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/components/inputComponents/rfidScanner.adoc
> +image::https://docs.sunfounder.com/projects/davinci-kit/en/latest/_images/image232.png[]
I can see that Joe's document is showing up the image from our repository try it.
image::../../img/rotary_encoder_circuit.png[]

2023-11-03 00:52 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/components/inputComponents/rfidScanner.adoc
> +
ok

2023-11-03 00:52 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/components/inputComponents/rfidScanner.adoc
> +:imagesdir: ../../images
This might be the culprit that causing issue for displaying image from the repository

2023-11-03 01:05 UTC, SwindleA commented on micronautpi4j-utils/src/docs/asciidoc/components/inputComponents/rfidScanner.adoc
> +image::https://docs.sunfounder.com/projects/davinci-kit/en/latest/_images/image232.png[]
When I build issue 98, the rotary encoder image isnt showing up.

2023-11-03 16:04 UTC, ruthvikm approved these changes
Looks good

2023-11-06 20:15 UTC, joefol approved these changes
Looks good to me

2023-11-06 20:18 UTC, adelgadoj3 approved these changes
Looks great!

2023-11-07 00:32 UTC, merged