Need to improve and add further information for this doc
oss-slu/Pi4Micronaut pull request #102
Opened 2023-10-30 20:40 UTC by adelgadoj3

2023-10-30 23:12 UTC, ruthvikm requested changes

2023-10-30 23:12 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/components/outputComponents/led.adoc
> +
Include Assembly Instructions section

2023-10-30 23:12 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/components/outputComponents/led.adoc
>  TODO: Create an example LED Controller
Get rid of this TODO

2023-10-30 23:12 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/components/outputComponents/led.adoc
> +
Move the below sections below circuit diagram and above constructors

2023-11-02 20:03 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/components/outputComponents/led.adoc
> +
Add Testing section and mention all the curl commands we use for this led component

2023-11-06 15:24 UTC, ruthvikm requested changes

2023-11-06 19:10 UTC, ruthvikm requested changes
- you have altered Led Controller class by adding led2. It's not necessary because it falls under multi component structure. Revert it back to one ledhelper.
- delete the :omega: variable on top.
- use the syntax like image::../../img/LED_circuit.png[] for circuit diagram

2023-11-06 20:59 UTC, SwindleA requested changes
two small things then it should be good.

2023-11-06 20:59 UTC, SwindleA commented on components/src/main/java/com/opensourcewithslu/components/controllers/LEDController.java
> +    @Get("/led")
The documentation says that this should be LEDOn. Change this to be `@Get("/LEDOn")`

2023-11-06 20:59 UTC, SwindleA commented on components/src/main/java/com/opensourcewithslu/components/controllers/LEDController.java
> +    public void checkLed(){
Have this match what is in the @Get

2023-11-06 21:05 UTC, ruthvikm commented on components/src/main/java/com/opensourcewithslu/components/controllers/LEDController.java
> +    @Get("/led")
Also make use all of the LED helper methods in the controller. We have deviceOn, deviceOff and switchState.

2023-11-06 21:07 UTC, ruthvikm requested changes

2023-11-06 21:07 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/components/outputComponents/led.adoc
> +image::/../../../../../asciidoc/img/LED_circuit.png[]
Fix the image path

2023-11-06 21:37 UTC, SwindleA approved these changes
ok

2023-11-06 21:42 UTC, ruthvikm approved these changes
Documentation looks good. Need to make use all of the LED helper methods in the controller. We have deviceOn, deviceOff and switchState. We will work on it with a new issue.

2023-11-06 21:42 UTC, merged