created outline for LCD documentation
oss-slu/Pi4Micronaut pull request #103
Opened 2023-10-30 21:27 UTC by jyanev

2023-11-17 17:55 UTC, ruthvikm requested changes
Change the LCD to LCD1602 where ever it is required

2023-11-17 17:55 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/components/outputComponents/lcdScreen.adoc
>  ==== LCD
This is LCD 1602 module which is different from standard LCD. Rename it to LCD 1602

2023-11-17 17:55 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/components/outputComponents/lcdScreen.adoc
> +This section provides details of the LCD (Liquid Crystal Display) circuit, including its components, assembly instructions, and functionality. The LCD is a M × N pixel screen that can be used to disp
Overview should be of LCD 1602. LCD1602, or 1602 character-type liquid crystal display, is a kind of dot matrix module to show letters, numbers, and characters and so on. It's composed of 5x7 or 5x11 dot matrix positions; each position can display one character. There's a dot pitch between two characters and a space between lines, thus separating characters and lines. The number 1602 means on the display, 2 rows can be showed and 16 characters in each.

2023-11-17 17:55 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/components/outputComponents/lcdScreen.adoc
> +. LCD
Change it to LCD1602

2023-11-17 17:55 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/img/lcd-circuit.png
Rename it

2023-11-17 20:04 UTC, SwindleA requested changes

2023-11-21 18:13 UTC, SwindleA approved these changes
Looks good

2023-11-21 18:39 UTC, ruthvikm approved these changes
Looks good

2023-11-21 18:39 UTC, merged