Fixes 127
oss-slu/Pi4Micronaut pull request #130
Opened 2023-11-30 00:03 UTC by adelgadoj3

Resolved toc and image improvements. Need to resolve white bar at bottom of screen.
![image](https://github.com/oss-slu/Pi4Micronaut/assets/123115416/2bf3e804-c5b2-44a6-8c7d-86dddc8f2139)

2023-11-30 17:58 UTC, adelgadoj3 commented
Increased the size of the image and eliminated white space. Only issue now is adding the links in the header, which is proving to be difficult. That file is still local and has not been pushed. When adding the links the rest of the page begins to have issues, furthermore the paths for the links are broken. So they cannot be used.

![image](https://github.com/oss-slu/Pi4Micronaut/assets/123115416/49c40118-3d50-470d-b090-c5774831dd1c)

2023-12-02 21:35 UTC, ruthvikm requested changes
I can see this $END$ in top left corner

![image](https://github.com/oss-slu/Pi4Micronaut/assets/116761292/34d54931-2f70-4ba3-8009-6eed9fa5d360)

I removed the $END$ from docinfo.html and now the introduction is behind the header
![image](https://github.com/oss-slu/Pi4Micronaut/assets/116761292/65f3d0ee-ae2f-4401-b768-931a536b7a07)

2023-12-05 01:17 UTC, SwindleA requested changes

2023-12-05 01:17 UTC, SwindleA commented on micronautpi4j-utils/src/docs/asciidoc/docinfo.html
> +$END$
I think this causes everything to be miss aligned.

2023-12-05 01:29 UTC, ruthvikm approved these changes
Looks good

2023-12-05 01:34 UTC, SwindleA approved these changes
good

2023-12-05 01:34 UTC, merged