DI changes for all components
oss-slu/Pi4Micronaut pull request #135
Opened 2024-01-24 22:27 UTC by joefol

2024-01-29 02:32 UTC, ruthvikm requested changes

2024-01-29 02:32 UTC, ruthvikm commented on micronautpi4j-utils/src/main/java/com/opensourcewithslu/outputdevices/LEDHelper.java
>      public void deviceOn()
Change the function name to ledOn()

2024-01-29 02:32 UTC, ruthvikm commented on micronautpi4j-utils/src/main/java/com/opensourcewithslu/outputdevices/LEDHelper.java
> +            log.trace("Turning on LED");
use log.info instead of trace

2024-01-29 02:32 UTC, ruthvikm commented on micronautpi4j-utils/src/main/java/com/opensourcewithslu/outputdevices/LEDHelper.java
>      //end::method[]
Change the function name to ledOff()

2024-01-29 02:32 UTC, ruthvikm commented on micronautpi4j-utils/src/main/java/com/opensourcewithslu/outputdevices/LEDHelper.java
> +            log.trace("Turning off LED");
use log.info

2024-01-29 02:32 UTC, ruthvikm commented on components/src/main/java/com/opensourcewithslu/components/controllers/LEDController.java
>          ledHelper.deviceOn();
it should be ledhelper.ledOff();

2024-01-29 02:32 UTC, ruthvikm commented on components/src/main/java/com/opensourcewithslu/components/controllers/LEDController.java
>          ledHelper.deviceOff();
it should be ledhelper.ledOn();

2024-01-29 20:54 UTC, ruthvikm reviewed
Looks good

2024-01-31 22:11 UTC, joefol commented
Closing this PR because DI changes not needed.

2024-01-31 22:11 UTC, closed without merging