Cleaning up code
oss-slu/Pi4Micronaut pull request #138
Opened 2024-01-31 22:41 UTC by joefol

2024-02-01 20:35 UTC, joefol commented
I think there might be an issue with the MultipinConfiguration class. All components using it (RGB, rotary encoder) get ambiguous dependency warnings.

2024-02-01 20:53 UTC, joefol commented
Also there are no log messages implemented for the RFID scanner or for some methods in some of the other components.

2024-02-02 01:57 UTC, ruthvikm requested changes
I can see few lambda expression exceptions. Please fix them.
<img width="352" alt="image" src="https://github.com/oss-slu/Pi4Micronaut/assets/116761292/29a1d7ac-00ad-49d0-850f-50b5cd1ea674">

2024-02-02 03:19 UTC, ruthvikm reviewed
The exception "Ambiguous dependency: there are multiple beans that match the injection point" occurs due to the use of MuiltiPinConfiguration.java class that being a hub for PWMMultiPin and DigitalInputMultipin configs which are required for rgb led and rotary-encoder respectively.  The Dependency Injection gets confused here between these two beans. This expection can be used to create a new issue.

2024-02-03 21:11 UTC, SwindleA requested changes
Looks good. I think we should build and run the project before merging. We can do this during the next meeting.

2024-02-04 16:31 UTC, ruthvikm requested changes

2024-02-04 16:31 UTC, ruthvikm commented on components/src/main/java/com/opensourcewithslu/components/controllers/rgbController.java
>      private static final Logger log = LoggerFactory.getLogger(rgbController.class);
Get rid of this, we didn't write any log messages here.

2024-02-04 16:31 UTC, ruthvikm commented on micronautpi4j-utils/src/main/java/com/opensourcewithslu/outputdevices/RGBLEDHelper.java
> +        log.info("setting the color and frequency via hex and int");
Change this log message in RGBHelper class. Here it is "Setting the color via Hex and a list of frequencies(RGB)"

2024-02-04 16:31 UTC, ruthvikm commented on micronautpi4j-utils/src/main/java/com/opensourcewithslu/outputdevices/RGBLEDHelper.java
> +        log.info("set green and set frequency");
Change this to "Setting Green color and it's frequency"

2024-02-04 16:31 UTC, ruthvikm commented on micronautpi4j-utils/src/main/java/com/opensourcewithslu/outputdevices/RGBLEDHelper.java
> +        log.info("turning off each LED pin");
Change the log message to "Turning off RGB LED"

2024-02-04 18:21 UTC, joefol commented
> Looks good. I think we should build and run the project before merging. We can do this during the next meeting.

It builds successfully on my machine, but I haven't ran it on a pi.

2024-02-04 22:08 UTC, ruthvikm reviewed
Looks good. Once we test this on pi, we can merge this pull request.

2024-02-04 22:47 UTC, ruthvikm requested changes

2024-02-04 22:47 UTC, ruthvikm commented on components/src/main/java/com/opensourcewithslu/components/controllers/RotaryEncoderController.java
> +                                   @Named("rotary-encoder-2")MultipinConfiguration rotaryEncoder2){
We didn't use this rotary-encoder-2, I think we can get rid off it.

2024-02-08 14:36 UTC, ruthvikm approved these changes
Tested most of the components. Everything works fine

2024-02-08 14:39 UTC, SwindleA approved these changes
Looks good.

2024-02-08 14:42 UTC, merged