added getting starting asciidoc for getting pi4micronaut working with…
oss-slu/Pi4Micronaut pull request #141
Opened 2024-02-05 19:04 UTC by jyanev

… raspberry pi

2024-02-12 00:25 UTC, ruthvikm requested changes

2024-02-12 00:25 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/Introduction/gettingStarted.adoc
> +. Enter the following command into the terminal to build the jar file: "./gradlew"
the command is "./gradlew build"

2024-02-12 00:25 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/Introduction/gettingStarted.adoc
> +. Navigate to the file directory containing the Pi4Micronaut library
This should be Pi4Micronaut root directory.

2024-02-12 00:25 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/Introduction/gettingStarted.adoc
> +==== Install the Raspberry Pi Imager
Section - Installing Raspberry Pi OS
write about Imager under this section with a link

2024-02-15 05:17 UTC, ruthvikm requested changes

2024-02-15 05:17 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/Introduction/gettingStarted.adoc
Mention in Note: saying this file is to build and run the jar from pi4micronaut project and not a guide to use pi4micronaut library in other projects

2024-02-15 05:17 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/Introduction/gettingStarted.adoc
> +. Grab an SD card and get it hooked up to your computer.
Use official Raspberry pi installation guide with a link and pickup writing from there.
https://www.raspberrypi.com/documentation/computers/getting-started.html#install-using-imager

2024-02-15 05:17 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/Introduction/gettingStarted.adoc
> ++
Get rid of the above instructions and put a Note: Use the same wifi network setting up raspberry pi

2024-02-15 05:17 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/Introduction/gettingStarted.adoc
> +. Get the IP address of your Pi and SSH into it
we can use hostname as well. change it to "Hostname or IP address" for ssh

2024-02-15 05:17 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/Introduction/gettingStarted.adoc
> +sudo apt install openjdk-17-jdk -y
sudo apt-get install default-jdk

use this for installing java because we use java 11

2024-02-15 05:17 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/Introduction/gettingStarted.adoc
> +
"sudo apt-get upgrade" to update all the packages

2024-02-15 05:17 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/Introduction/gettingStarted.adoc
> +
"sudo apt-get install pigpio" we use this to install PIGPIO

2024-02-15 05:17 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/Introduction/gettingStarted.adoc
> +. Enter the following command to test the turn on funcion for an LED light: "curl http://localhost:8080/led/LedOn"
They need to setup the circuit according to our documentation of LED to test it.

2024-02-15 05:17 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/Introduction/gettingStarted.adoc
> +. Enter the following command to test the turn on funcion for an LED light: "curl http://localhost:8080/led/LedOn"
Before curl commands, we need to run the jar file using "sudo java -jar components-0.1-all.jar" and add a screenshot of how it looks like

2024-02-15 05:17 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/Introduction/gettingStarted.adoc
> +. If this command works, congratulations! You have successfully used our Pi4Micronaut library!
No, this is not for using Pi4Micronaut library. To build, run and test the Pi4Micronaut components.

2024-02-15 05:19 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/Introduction/gettingStarted.adoc
> +. Before beginning the setup, ensure that your Raspberry Pi and your system are both connected to the same network
we need to clone the library from github

2024-02-15 05:21 UTC, ruthvikm reviewed
Mention to clone the library before they try to build

2024-02-16 00:37 UTC, ruthvikm requested changes

2024-02-16 00:37 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/Introduction/gettingStarted.adoc
> +. *IMPORTANT!!* When choosing the OS, click "*CHOOSE OS*" -> "*Raspberry Pi OS (other)*" -> "*Raspberry Pi OS (Legacy, 64-bit) Lite*"
They can use any type of OS

2024-02-16 00:37 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/Introduction/gettingStarted.adoc
> +scp components-0.1-all.jar {username}@{hostname}:~
The current working directory of the user should be ../Pi4Micronaut/components/build/libs/ to use the above SCP command

2024-02-16 00:37 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/Introduction/gettingStarted.adoc
> +The output should look like this:
Mention that a Micronaut localhost server will be running once you run the jar file on Pi

2024-02-16 00:37 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/Introduction/gettingStarted.adoc
> +. Choose your desired protocol
Mention to enable I2c, SPI etc which we used in our library

2024-02-16 00:37 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/Introduction/gettingStarted.adoc
> +. Reboot when prompted to
Add a screenshot

2024-02-16 01:48 UTC, SwindleA requested changes
The images are missing and one of the curl commands is incorrect. Otherwise it looks great.

2024-02-16 01:48 UTC, SwindleA commented on micronautpi4j-utils/src/docs/asciidoc/Introduction/gettingStarted.adoc
> +"curl http://localhost:8080/led/LedOn"
change the curl command to be "curl http://localhost:8080/led/ledOn"

2024-02-16 01:48 UTC, SwindleA commented on micronautpi4j-utils/src/docs/asciidoc/Introduction/gettingStarted.adoc
> +image::imager_settings1.png[]
Looks like you didnt push the images to the repo. make sure they are in the 'micronautpi4j-utils/build/docs/asciidoc/img/' folder.

2024-02-16 01:59 UTC, SwindleA requested changes
I missed saying you need to add 'include::Introduction/gettingStarted.adoc[]' to the index.adoc in the place that this section is supposed to appear in the documentation.

2024-02-16 02:12 UTC, SwindleA approved these changes
Looks good. This is what it looks like in the table of contents.
![image](https://github.com/oss-slu/Pi4Micronaut/assets/60612512/7292c12b-8b06-4923-925c-808990a80c3c)

2024-02-16 02:36 UTC, ruthvikm approved these changes

2024-02-16 02:36 UTC, merged