Touch Switch Implementation Issue 144
oss-slu/Pi4Micronaut pull request #152
Opened 2024-02-14 23:07 UTC by joefol

Implementing touch switch helper and controller.

2024-02-15 04:57 UTC, ruthvikm requested changes

2024-02-15 04:57 UTC, ruthvikm commented on components/src/main/java/com/opensourcewithslu/components/controllers/TouchSwitchController.java
> +    public TouchSwitchController(DigitalInput touchSwitch,
Use @Named to fetch configuration from Application.yml file for touchSwitch and led

2024-02-15 04:57 UTC, ruthvikm commented on components/src/main/java/com/opensourcewithslu/components/controllers/TouchSwitchController.java
> +                ledHelper.switchState();
Use ledOn() and ledOff() here. For some reason if the led turned on in the initial state of the application, switching state actions might get swapped. One more approach is to set led off initially via constructor

2024-02-15 04:57 UTC, ruthvikm commented on components/src/main/java/com/opensourcewithslu/components/controllers/TouchSwitchController.java
> +    }
add disable function and make use of removeEventListener from helper

2024-02-16 02:38 UTC, ruthvikm requested changes

2024-02-16 02:38 UTC, ruthvikm commented on components/src/main/java/com/opensourcewithslu/components/controllers/TouchSwitchController.java
> +            if(touchSwitchHelper.isTouched){
I don't think we need this if else block here

2024-02-18 22:37 UTC, ruthvikm reviewed
Add comments which are appropriate for javadocs

2024-02-18 22:37 UTC, ruthvikm submitted a review, later dismissed

2024-02-18 22:54 UTC, SwindleA approved these changes

2024-02-19 18:04 UTC, adelgadoj3 approved these changes

2024-02-19 20:33 UTC, ruthvikm approved these changes

2024-02-19 20:34 UTC, merged