Active Buzzer
oss-slu/Pi4Micronaut pull request #160
Opened 2024-02-23 20:49 UTC by adelgadoj3

Resolves active buzzer helper and controller. Passive Buzzer needs more work done. Will be a new issue for next sprint.

2024-02-23 21:25 UTC, ruthvikm requested changes
Test it again on pi and check the buzzer functions and corresponding log messages

2024-02-23 21:25 UTC, ruthvikm commented on components/src/main/java/com/opensourcewithslu/components/controllers/ActiveBuzzerController.java
> +//import com.pi4j.io.gpio.digital.DigitalOutput;
get rid of unnecessary comments

2024-02-23 21:25 UTC, ruthvikm commented on pi4micronaut-utils/src/main/java/com/opensourcewithslu/outputdevices/ActiveBuzzerHelper.java
> +//import com.pi4j.io.gpio.digital.DigitalOutput;
remove this import

2024-02-23 21:25 UTC, ruthvikm commented on pi4micronaut-utils/src/main/java/com/opensourcewithslu/outputdevices/ActiveBuzzerHelper.java
> +        this.activeBuzzer.on(100, 3000); //Duty Cycle must be 100 and Frequency should be 440.
change the frequency to 440

2024-02-23 21:25 UTC, ruthvikm commented on pi4micronaut-utils/src/main/java/com/opensourcewithslu/outputdevices/ActiveBuzzerHelper.java
> +            log.info("Buzzer on.");
the log.info message "Buzzer On" comes from activeBuzzerOn(), change the message to "Buzzer turns on for 10 sec"

2024-02-23 21:25 UTC, ruthvikm commented on pi4micronaut-utils/src/main/java/com/opensourcewithslu/outputdevices/ActiveBuzzerHelper.java
> +            log.info("Buzzer off.");
remove this log message

2024-02-23 21:25 UTC, ruthvikm commented on pi4micronaut-utils/src/main/java/com/opensourcewithslu/outputdevices/ActiveBuzzerHelper.java
> +    public void alertTone(){
change the function name to beep. add a log info message "Beeps for 2 sec"

2024-02-23 21:25 UTC, ruthvikm commented on pi4micronaut-utils/src/main/java/com/opensourcewithslu/outputdevices/ActiveBuzzerHelper.java
> +    public void buzzerTest(){
change the function name to morseCodeTone

2024-02-23 21:25 UTC, ruthvikm commented on pi4micronaut-utils/src/main/java/com/opensourcewithslu/outputdevices/ActiveBuzzerHelper.java
> +        int [] morseCodePi = {200,600,600,200,200,200}; // Durations for .--. .. (pi in Morse)
remove the Pi at the end of variable name

2024-02-23 21:25 UTC, ruthvikm commented on pi4micronaut-utils/src/main/java/com/opensourcewithslu/outputdevices/ActiveBuzzerHelper.java
> +
add a log message "Playing morse code"

2024-02-23 22:24 UTC, SwindleA requested changes
just a few javadoc comments missing. It builds correctly. I assume someone else will test the component.

2024-02-23 22:24 UTC, SwindleA commented on pi4micronaut-utils/src/main/java/com/opensourcewithslu/outputdevices/ActiveBuzzerHelper.java
> +    public void alertTone(){
needs javadoc comment

2024-02-23 22:24 UTC, SwindleA commented on pi4micronaut-utils/src/main/java/com/opensourcewithslu/outputdevices/ActiveBuzzerHelper.java
> +    public void constantTone(){
Needs javadoc comment

2024-02-23 22:24 UTC, SwindleA commented on pi4micronaut-utils/src/main/java/com/opensourcewithslu/outputdevices/ActiveBuzzerHelper.java
> +    public void buzzerTest(){
add javadoc comment

2024-02-23 22:25 UTC, ruthvikm commented
> just a few javadoc comments missing. It builds correctly. I assume someone else will test the component.

We have tested it on pi and it works

2024-02-24 20:26 UTC, ruthvikm requested changes

2024-02-24 20:26 UTC, ruthvikm commented on components/src/main/java/com/opensourcewithslu/components/controllers/ActiveBuzzerController.java
> +     * Emits a constant tone from the active buzzer for a duration of 20 seconds.
This comment doesn't justify the function below

2024-02-24 20:26 UTC, ruthvikm commented on pi4micronaut-utils/src/main/java/com/opensourcewithslu/outputdevices/ActiveBuzzerHelper.java
> + * The BuzzerHelper class contains methods that pertain to the control of the active and passive buzzers.
no passive buzzer here

2024-02-26 01:56 UTC, ruthvikm approved these changes

2024-02-26 04:19 UTC, SwindleA requested changes
Looks good. One small typo regarding the constructor javadoc.

2024-02-26 04:19 UTC, SwindleA commented on pi4micronaut-utils/src/main/java/com/opensourcewithslu/outputdevices/ActiveBuzzerHelper.java
> +/*
This line needs a second '*' for the javadoc to generate. So line 9 needs to be /**

2024-02-26 19:41 UTC, SwindleA approved these changes
Looks good. Javadocs build correctly

2024-02-26 19:41 UTC, merged