Passive Buzzer Implementation
oss-slu/Pi4Micronaut pull request #182
Opened 2024-02-27 15:33 UTC by adelgadoj3

Implemented the passive buzzer helper. Need to continue testing to obtain audio output from buzzer. Currently there is no audio output.

2024-02-27 19:13 UTC, joefol commented
Make sure you are merging into develop and not main.

2024-02-28 19:18 UTC, adelgadoj3 commented
> Make sure you are merging into develop and not main.

Thanks for the catch Joe.

2024-03-10 22:55 UTC, SwindleA requested changes
Looks good. a couple small javadoc issues. Builds correctly. I did not test it.

2024-03-10 22:55 UTC, SwindleA commented on pi4micronaut-utils/src/main/java/com/opensourcewithslu/outputdevices/PassiveBuzzerHelper.java
> +public class PassiveBuzzerHelper {
A class description is needed. javadoc

2024-03-10 22:55 UTC, SwindleA commented on pi4micronaut-utils/src/main/java/com/opensourcewithslu/outputdevices/PassiveBuzzerHelper.java
> +    public void passiveBuzzerOn(int passBuzzDC, int passiveBuzzerFreq){
parameter descriptions are needed. javadoc

2024-03-11 22:43 UTC, SwindleA approved these changes
looks good

2024-03-13 01:06 UTC, ruthvikm requested changes
Need to change few function names where 'Test' is used, because in future we are going to write test cases for all the components. These function names leads to discrepancies.

2024-03-13 01:06 UTC, ruthvikm commented on pi4micronaut-utils/src/main/java/com/opensourcewithslu/outputdevices/PassiveBuzzerHelper.java
> +    protected int passiveBuzzerFreq = 440;
Variables which are not private requires Javadoc comments

2024-03-13 01:06 UTC, ruthvikm commented on pi4micronaut-utils/src/main/java/com/opensourcewithslu/outputdevices/PassiveBuzzerHelper.java
> +    public void functionalityTest(){
Test cannot be used as function names, change it

2024-03-13 23:38 UTC, ruthvikm approved these changes

2024-03-13 23:38 UTC, merged