outlined ultrasound sensor component
oss-slu/Pi4Micronaut pull request #185
Opened 2024-03-04 21:12 UTC by jyanev

2024-03-13 01:17 UTC, ruthvikm requested changes
Need javadoc comments for constructor.
Need to add @return in the javadoc comments for getDistanceInMeters()  and getDistanceInCentimeter()

2024-03-13 01:27 UTC, ruthvikm requested changes
We need to work on a new branch that use develop as base. But you created issue-165 branch that uses main branch as base. This results in conflicts.

Steps to resolve this issue:

- clone the repo
- checkout to develop
- create a new branch with name "ultra_sonic_support"
- copy the controller and helper into the new branch from the current one.
- add the configuration details to application.yml
- add the missing javadoc comments/@return details.
- commit and push

2024-03-14 00:43 UTC, ruthvikm approved these changes

2024-03-14 00:58 UTC, SwindleA requested changes
remove the html files. I did not test the components. otherwise its good

2024-03-14 00:58 UTC, SwindleA commented on pi4micronaut-utils/src/docs/javadoc/allclasses-index.html
>  <div class="col-last even-row-color all-classes-table all-classes-table-tab2">
all of these html files do not need to be part of the merge. they will be generated when published.

2024-03-14 01:07 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/javadoc/allclasses-index.html
>  <div class="col-last even-row-color all-classes-table all-classes-table-tab2">
When published these will be copied on to the gh-pages branch. They will not generate automatically because we didn't create any workflow that builds javadoc

2024-03-14 04:27 UTC, merged