Adoc Updates
oss-slu/Pi4Micronaut pull request #188
Opened 2024-03-13 22:00 UTC by joefol

Steps for creating a Micronaut application and configurations for using Pi4Micronaut.

2024-03-13 23:56 UTC, SwindleA approved these changes
looks good

2024-03-14 00:11 UTC, ruthvikm requested changes

2024-03-14 00:11 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/Introduction/howToUsePi4Micronaut.adoc
> ++
There is an additional + sign here.

2024-03-14 00:11 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/Introduction/howToUsePi4Micronaut.adoc
> +. Go to the configuration file:
Make this more clear. Go to the application.yml file to add configuration of  your circuit setup

2024-03-14 00:11 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/Introduction/howToUsePi4Micronaut.adoc
> +Here we are specifying a led as a digital output type with name LED, address 17, etc.
add a link to led documentation here for more info about configuration

2024-03-14 00:11 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/Introduction/howToUsePi4Micronaut.adoc
> +. Create a new class in the com.demoPi4Micronaut directory
Create a new class in the project's src directory as shown below.

2024-03-14 00:11 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/Introduction/howToUsePi4Micronaut.adoc
> +This is where code will be written to implement a LED light using the Pi4Micronaut library.
This is where you use the implemented LED functions from Pi4Micronaut library.

2024-03-14 00:11 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/Introduction/howToUsePi4Micronaut.adoc
> +. Now that the code for the LED has been written, see our other documentation on building and running
Since the two sections are next to each other, we don't need this

2024-03-14 01:39 UTC, SwindleA approved these changes

2024-03-14 01:39 UTC, SwindleA commented on pi4micronaut-utils/src/docs/asciidoc/Introduction/howToUsePi4Micronaut.adoc
> ++
It would be great if the user could copy paste the example code.

2024-03-14 02:09 UTC, ruthvikm requested changes

2024-03-14 03:38 UTC, ruthvikm approved these changes
Looks good.

2024-03-14 03:38 UTC, merged