Passive Buzzer Documentation
oss-slu/Pi4Micronaut pull request #208
Opened 2024-03-20 22:14 UTC by adelgadoj3

Created passive buzzer documentation, added circuit diagram, and added link to index documentation

2024-03-21 16:27 UTC, ruthvikm requested changes
- [ ] Add example controller at the end.
- [ ] Add Passive Buzzer Javadoc in the functionality section. Refer to touch switch documentation.

2024-03-21 17:01 UTC, joefol approved these changes
Looks good to me!

2024-03-21 18:22 UTC, adelgadoj3 commented
> * [x]  Add example controller at the end.
> * [x]  Add Passive Buzzer Javadoc in the functionality section. Refer to touch switch documentation.

Should I incorporate the schematic diagram and/or the buzzer diagram as well?

![image](https://github.com/oss-slu/Pi4Micronaut/assets/123115416/b171d3e6-4c27-41f8-85c0-36a7e68c8fa4)


![image](https://github.com/oss-slu/Pi4Micronaut/assets/123115416/72e5073b-0467-439b-83ee-1dceb22f0eb5)

2024-03-21 19:24 UTC, ruthvikm requested changes
To add example controller, you need to add //tag::ex[] in passivebuzzerController class

2024-03-21 19:24 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/index.adoc
> +include :: components/outputComponents/passivebuzzer.adoc[]
Remove space here -  include::components....

2024-03-21 19:24 UTC, ruthvikm commented
Schematic diagram will be useful

2024-03-21 19:35 UTC, SwindleA requested changes
other than that one possible issue. It looks good.

2024-03-21 19:35 UTC, SwindleA commented on pi4micronaut-utils/src/docs/asciidoc/components/outputComponents/passivebuzzer.adoc
> +include::../../../../../../components/src/main/java/com/opensourcewithslu/components/controllers/PassiveBuzzerController.java[tag=ex]
The example controller is not showing up for me.

2024-03-21 19:37 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/components/outputComponents/passivebuzzer.adoc
> +include::../../../../../../components/src/main/java/com/opensourcewithslu/components/controllers/PassiveBuzzerController.java[tag=ex]
tag was not added to the controller

2024-03-21 19:49 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/components/outputComponents/passivebuzzer.adoc
> +
Add constructors and methods senction with passiveBuzzer javadoc link.
https://oss-slu.github.io/Pi4Micronaut/javadoc/com/opensourcewithslu/outputdevices/PassiveBuzzerHelper.html

2024-03-23 00:54 UTC, ruthvikm requested changes
Resolve conflicts

2024-03-24 00:16 UTC, ruthvikm requested changes

2024-03-24 00:16 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/components/outputComponents/passivebuzzer.adoc
> +image::buzzer-SD.png[]
this image was not uploaded

2024-03-24 00:30 UTC, adelgadoj3 commented on pi4micronaut-utils/src/docs/asciidoc/components/outputComponents/passivebuzzer.adoc
> +image::buzzer-SD.png[]
I added the image in the active buzzer documentation issue.

2024-03-24 03:12 UTC, ruthvikm approved these changes

2024-03-25 00:12 UTC, ruthvikm requested changes
Resolve conflicts

2024-03-25 00:41 UTC, ruthvikm approved these changes

2024-03-25 00:42 UTC, merged