197 active buzzer documentation
oss-slu/Pi4Micronaut pull request #214
Opened 2024-03-21 18:18 UTC by adelgadoj3

Initial draft of the active buzzer documentation.

2024-03-21 19:47 UTC, SwindleA requested changes
looks good other than the couple noted issues

2024-03-21 19:47 UTC, SwindleA commented on pi4micronaut-utils/src/docs/asciidoc/components/outputComponents/activebuzzer.adoc
> +==== Components
This section and the following sections need a 5th = for the proper indentation

2024-03-21 19:47 UTC, SwindleA commented on pi4micronaut-utils/src/docs/asciidoc/components/outputComponents/activebuzzer.adoc
> +include::../../../../../../components/src/main/java/com/opensourcewithslu/components/controllers/ActiveBuzzerController.java[tag=ex]
this isnt not showing up because the controller needs the `//tag::ex[]` and `//end::ex[]`  tags.

2024-03-21 19:47 UTC, ruthvikm requested changes

2024-03-21 19:47 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/components/outputComponents/activebuzzer.adoc
> +==== Components
Should be 5 =====

2024-03-21 19:47 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/components/outputComponents/activebuzzer.adoc
> +==== Assembly Instructions
same here 5 =

2024-03-21 19:47 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/components/outputComponents/activebuzzer.adoc
> +==== Circuit Diagram
.

2024-03-21 19:47 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/components/outputComponents/activebuzzer.adoc
> +----
Add these tags //tag=ex[] and //end=ex[] to activeBuzzerController

2024-03-21 19:47 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/components/outputComponents/activebuzzer.adoc
> +
Add constructors and methods section by add activeBuzzer javadoc here 
https://oss-slu.github.io/Pi4Micronaut/javadoc/com/opensourcewithslu/outputdevices/ActiveBuzzerHelper.html

2024-03-23 00:55 UTC, ruthvikm requested changes
Resolve conflicts

2024-03-24 03:12 UTC, ruthvikm approved these changes
looks good

2024-03-24 14:55 UTC, SwindleA approved these changes
looks good

2024-03-25 00:09 UTC, merged