PIR Sensor Documentation
oss-slu/Pi4Micronaut pull request #216
Opened 2024-03-22 20:49 UTC by SwindleA

PIR sensor documentation

2024-03-26 01:17 UTC, ruthvikm requested changes

2024-03-26 01:17 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/components/inputComponents/pirSensor.adoc
> +https://github.com/oss-slu/Pi4Micronaut/edit/develop/micronautpi4j-utils/src/docs/asciidoc/components/inputComponents/pirSensor.adoc[Improve this doc]
It's pointing to old one. Please check.

2024-03-27 07:12 UTC, ruthvikm approved these changes

2024-03-27 21:01 UTC, adelgadoj3 approved these changes
Looks good to me!

2024-03-27 21:02 UTC, joefol requested changes
Looks good

2024-03-27 21:02 UTC, joefol commented on components/src/main/java/com/opensourcewithslu/components/controllers/PIRSensorController.java
> +    public PIRSensorController(@Named("pir-sensor")DigitalInput pirSensor,@Named("rgb-led-2") MultiPinConfiguration rgbLed) {
Put a space between '@Named("pir-sensor") and DigitalInput and a space between the comma and '@Named()

2024-03-27 21:05 UTC, merged