rm sections 4,5 from docs; added descriptions for i2c, pwm...
oss-slu/Pi4Micronaut pull request #218
Opened 2024-03-23 21:05 UTC by jyanev

2024-04-08 20:57 UTC, SwindleA requested changes
typos

2024-04-08 20:57 UTC, SwindleA commented on pi4micronaut-utils/src/docs/asciidoc/components/commun_WithHardware/i2c.adoc
> +The I2C protocol uses two wired: SDA (serial data) and SCL (serial clock). This protocol allows for communication between
wires*

2024-04-08 20:57 UTC, SwindleA commented on pi4micronaut-utils/src/docs/asciidoc/components/commun_WithHardware/i2c.adoc
> +The I2C module is a chip that can expand the I/O ports of the Adruino using the I2C protocol.
what arduino? do you mean LCD?

2024-04-08 20:57 UTC, SwindleA commented on pi4micronaut-utils/src/docs/asciidoc/components/inputComponents/pushButton.adoc
> +To see the constructor and methods of our TouchSwitchHelper class see our javadoc link:https://oss-slu.github.io/Pi4Micronaut/javadoc/com/opensourcewithslu/inputdevices/PushButtonHelper.html[here]
This is push button not touchswitch

2024-04-08 20:57 UTC, SwindleA commented on pi4micronaut-utils/src/docs/asciidoc/components/outputComponents/led.adoc
> +To see the constructor and methods of our UltraSonicSensor class see our javadoc link:https://oss-slu.github.io/Pi4Micronaut/javadoc/com/opensourcewithslu/outputdevices/LEDHelper.html[here]
LED not ultrasonic

2024-04-08 20:57 UTC, SwindleA commented on pi4micronaut-utils/src/docs/asciidoc/components/outputComponents/rgbLed.adoc
> +To see the constructor and methods of our UltraSonicSensor class see our javadoc link:https://oss-slu.github.io/Pi4Micronaut/javadoc/com/opensourcewithslu/outputdevices/RGBLEDHelper.html[here]
RGB not ultrasonic

2024-04-08 23:22 UTC, ruthvikm requested changes
Correct all the typos. Make sure all the Example controller are displayed in the documentation by defining appropriate tags in the controller classes.

2024-04-08 23:22 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/components/commun_WithHardware/i2c.adoc
> +The I2C LCD1602 consists of a normal LCD1602 and an I2C module that is attached to the back of the LCD.
Add "For Example" at the beginning

2024-04-08 23:22 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/components/commun_WithHardware/pwm.adoc
> +To define in application.yaml add digital-input as a field under pi4j, then add each component under digital-input. Each component will need:
This is about PWM, why to define under digital-input

2024-04-08 23:22 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/components/commun_WithHardware/spi.adoc
> +(https://docs.arduino.cc/tutorials/generic/introduction-to-the-serial-peripheral-interface/[Source: docs.arduino.cc])
Find something related to Raspberry pi. This might lead to confusion

2024-04-08 23:22 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/components/commun_WithHardware/spi.adoc
> +To define in application.yaml add digital-input as a field under pi4j, then add each component under digital-input. Each component will need:
This should be under SPI not digital-input

2024-04-08 23:22 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/components/inputComponents/touchSwitch.adoc
> +====== Touch Switch javadocs include methods for the touch switch component
Link to javadoc was already defined under Constructors and methods section. Remove this

2024-04-08 23:22 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/components/outputComponents/lcd1602.adoc
> +To see the constructor and methods of our UltraSonicSensor class see our javadoc link:https://oss-slu.github.io/Pi4Micronaut/javadoc/com/opensourcewithslu/outputdevices/LCD1602Helper.html[here]
This belongs to LCD not UltraSonicSensor

2024-04-09 19:08 UTC, ruthvikm requested changes
Few more typos need to be fixed

2024-04-09 19:08 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/components/commun_WithHardware/i2c.adoc
> +multiple devices using only two wires and unique addresses.
This should continue in the same line above

2024-04-09 19:08 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/components/commun_WithHardware/spi.adoc
> +The Serial Peripheral Interface (SPI) is a communication protocol used to transfer data between micro-computers like the Raspberry Pi and peripheral devices. These peripheral devices may be either se
We focus only on Raspberry Pi, get rid of other micro-computers

2024-04-09 19:08 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/components/commun_WithHardware/pwm.adoc
> +To define in application.yaml add pwm as a field under pi4j, then add each component under digital-input. Each component will need:
under pwm not digital-input

2024-04-09 19:08 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/components/commun_WithHardware/spi.adoc
> +
Replace microcontrollers with Raspberry Pi

2024-04-09 19:08 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/components/commun_WithHardware/spi.adoc
> +To define in application.yaml add spi as a field under pi4j, then add each component under digital-input. Each component will need:
under SPI not digital-input

2024-04-09 23:52 UTC, SwindleA requested changes
One last typo. Builds correctly.

2024-04-09 23:52 UTC, SwindleA commented on pi4micronaut-utils/src/docs/asciidoc/components/commun_WithHardware/i2c.adoc
> +It converts the signals from the Arduino into commands for the LCD.
Pi4Micronaut not Arduino

2024-04-10 00:08 UTC, jyanev commented on pi4micronaut-utils/src/docs/asciidoc/components/commun_WithHardware/i2c.adoc
> +It converts the signals from the Arduino into commands for the LCD.
it should be Raspberry Pi, rather than pi4micronaut I would think, right?

2024-04-10 00:10 UTC, SwindleA commented on pi4micronaut-utils/src/docs/asciidoc/components/commun_WithHardware/i2c.adoc
> +It converts the signals from the Arduino into commands for the LCD.
yes. Raspberry Pi. I misspoke.

2024-04-10 00:53 UTC, ruthvikm requested changes
- [x] In 4.1.2 Digital Output section, change the digital-input  to digital-output here - "then add each component under digital-input".
- [x] In 4.1.3 section, Example Multipin PWM declaration is not showing up.
- [x] In 4.1.4 Section, the example for PWM was given by using LED, but we didn't use PWM for LED. Instead change the LED to Buzzer and talk about it.
- [x] In 4.2.3 Section, the yaml configuration defined in the documentation is wrong replace it with actual configuration from application.yml
- [x] In 4.2.6 Section, the yaml configuration for ultrasonic sensor is not fully defined. Replace it with the actual configuration from application.yml
- [ ] In 4.3.1 Section, the yaml configuration is missing digital-output for LED and example controller is not displayed.
- [ ] In 4.3.2 Section, correct the RGB led yaml configuration
- [ ] In 4.3.3, LCD example controller is not displayed.
- [ ] In 4.3.4 & 4.3.5, add PWM above the buzzer configuration.
- [ ] All the curl command for the components are not formatted correctly. Ensure all of them look same.

2024-04-10 02:36 UTC, SwindleA approved these changes
👍

2024-04-10 18:30 UTC, ruthvikm approved these changes

2024-04-10 20:47 UTC, merged