Config Workflow Diagram in adoc. Issue 210
oss-slu/Pi4Micronaut pull request #219
Opened 2024-03-25 03:15 UTC by joefol

2024-04-08 14:16 UTC, ruthvikm approved these changes
Looks Good

2024-04-08 14:43 UTC, SwindleA approved these changes
Looks good. Im having unrelated gradle issues, so I did not test the build.

2024-04-08 15:59 UTC, adelgadoj3 approved these changes
Looks great!

2024-04-08 23:24 UTC, ruthvikm requested changes
Add a sentence that states if users want to use multiple components then the configuration should be defined in snake yaml structure

2024-04-09 19:00 UTC, ruthvikm requested changes

2024-04-09 19:00 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/components/commun_WithHardware.adoc
> +If a user wants to implement multiple hardware components then the configuration should be defined in the snake yml structure.
*an user

2024-04-09 20:58 UTC, joefol commented on pi4micronaut-utils/src/docs/asciidoc/components/commun_WithHardware.adoc
> +If a user wants to implement multiple hardware components then the configuration should be defined in the snake yml structure.
'A user' is grammatically correct I believe

2024-04-10 00:17 UTC, ruthvikm approved these changes

2024-04-10 00:17 UTC, merged