Fixes #221 Joss Paper
oss-slu/Pi4Micronaut pull request #222
Opened 2024-04-03 21:59 UTC by adelgadoj3

Created the foundation for the JOSS Submission. We can add or remove sections as needed.

2024-04-11 13:51 UTC, SwindleA commented
First full draft of the paper. More discussion on how the library works needs to be discussed.

2024-04-17 21:04 UTC, SwindleA commented
I am still trying to make sure the paper compiles correctly with the references. I just need a review on the contents of the paper.

2024-04-17 21:41 UTC, ruthvikm requested changes
Talk about the Raspberry Pi GPIO and how we are providing support for different hardware components.

2024-04-18 14:09 UTC, ruthvikm commented
> > Talk about the Raspberry Pi GPIO and how we are providing support for different hardware components. Significance of Pi4Micronaut is missing, explain how Pi4Micronaut application provides API interaction for each component and the different functionalities that we provide for hardware components. Also, talk about python dependency when it comes to Raspberry Pi GPIO interactions.
> 
> @ruthvikm The submission guidelines specifically say that the purpose of the software should be described for a non-specialist audience. So, talking about GPIO, API, and python versus java would be to specific towards programmers. Let me know if you disagree.
> 
> Submission [information:](https://joss.readthedocs.io/en/latest/submitting.html), see the section titled "What should my paper contain?".

@SwindleA - Guidelines says, summary should have a High-Level information focus for non-specialist audience. I think we can use statement of work section to write it up clearly. So that, the reviewers can understand our project. Get into the reviewer shoes and read the paper, you can feel what things are lacking in the paper to show it's significance.

2024-04-18 21:27 UTC, ruthvikm requested changes

2024-04-18 21:27 UTC, ruthvikm commented on joss/paper.md
> +authors:
Keep all the members as authors

2024-04-18 21:27 UTC, ruthvikm commented on joss/paper.md
> +The Pi4Micronaut library package can be found [here](https://central.sonatype.com/artifact/io.github.oss-slu/pi4micronaut-utils).
Make bullet points for the links instead of paragraph.

2024-04-18 21:27 UTC, ruthvikm commented on joss/paper.md
> +
For usage, talk about our OSS-SLU-CheckIn and Home_Automation projects as example use cases of  our library.

2024-04-18 21:27 UTC, ruthvikm commented on joss/paper.md
> +
Talk about Open Source with SLU and who's funding us.

2024-04-22 23:51 UTC, kate-holdener reviewed
I added some suggestions for improvement.

2024-04-22 23:51 UTC, kate-holdener commented on joss/paper.md
> +Pi4Micronaut's utilization of the Micronaut framework allows for HTTP requests to interact with the software. These
Maybe change the subject of the sentence here. Something like  "The Micronaut framework, widely used for building web applications and microservices, handles HTTP requests. These requests are then passed to Micronaut's application controller, which is custom code written for each specific web application. The application controller can make calls to the Pi4Micronaut library to interact with the hardware components. Pi4Micronaut library uses Pi4J for low-level hardware interaction. Thus, Pi4Micronaut provides an abstraction layer between Pi4J utilities and Micronaut framework, allowing the developer to focus on the application logic.

2024-04-22 23:51 UTC, kate-holdener commented on joss/paper.md
> +Pi4Micronaut's utilization of the Micronaut framework allows for HTTP requests to interact with the software. These
It may be good to create a diagram illustrating this description.

2024-04-22 23:51 UTC, kate-holdener commented on joss/paper.md
> +that are connected to the Raspberry Pi. For a developer, Pi4Micronaut fills the need of a Java framework for IoT applications.
I would make this a separate paragraph. Again, I suggest to use simpler and more direct wording. With Micronaut and Pi4Micronaut, developers can create web applications to monitor and control their research instruments. Web application is beneficial in cases where multiple researchers need to interact with the same instruments. Web application running on a Raspberry Pi will provide access to the instruments to any user on the same Wi-Fi network. For stricter access control, applications can utilize authentication and authorization mechanisms.

2024-04-22 23:51 UTC, kate-holdener commented on joss/paper.md
> +For researchers, a major component of their work is data gathering. While there are many instances when they can simply
Again, I suggest changing the subject of your sentence: Data gathering is a major element of research. There are many research instruments that can be simply connected to a personal computer and utilized as is. However, there are circumstances for when customized instruments need to be developed. 

Then you would proceed to your "The single board Raspberry Pi computer ... " sentence

2024-09-22 16:30 UTC, kungfuchicken commented
@ruthvikm i don't want to see this go stale. checking in on readiness/progress. any concerns? it looks good to me.

2024-09-22 16:31 UTC, kungfuchicken approved these changes
lgtm;

2024-09-22 20:27 UTC, ruthvikm commented
> @ruthvikm i don't want to see this go stale. checking in on readiness/progress. any concerns? it looks good to me.

Working on it. Paper need some minor tweaks. I'll close this pull request by end of this week.

2024-09-23 19:26 UTC, ruthvikm commented
Closing this Pull request and deleting 221-joss-paper branch as it used develop branch as base. Working on a new branch to avoid conflicts.

2024-09-23 19:26 UTC, closed without merging