Started basis of photoresistorSensor documentation
oss-slu/Pi4Micronaut pull request #227
Opened 2024-04-10 21:57 UTC by adelgadoj3

Began process for PhotoResistorSensor documentation.

2024-04-10 21:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/oss-slu/Pi4Micronaut?pullRequest=227) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/oss-slu/Pi4Micronaut?pullRequest=227) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/oss-slu/Pi4Micronaut?pullRequest=227) it.</sub>

2024-04-21 14:59 UTC, SwindleA requested changes
see the comments. Also the component needs to be added to the index.adoc so that it shows up in the documentation.

2024-04-21 14:59 UTC, SwindleA commented on pi4micronaut-utils/src/docs/asciidoc/components/inputComponents/photoresistorSensor.adoc
> +This section provides the details of the PhotoResistor Sensor, also known as the light sensor, circuit, including its components, assembly instructions, and functionality.
reword this sentence. One suggestion is to move the comment about the light sensor to a separate sentence.

2024-04-21 14:59 UTC, SwindleA commented on pi4micronaut-utils/src/docs/asciidoc/components/inputComponents/photoresistorSensor.adoc
> +* Power source (appropriate voltage, typically 3.3V or 5V)
the voltage should be specified.

2024-04-21 14:59 UTC, SwindleA commented on pi4micronaut-utils/src/docs/asciidoc/components/inputComponents/photoresistorSensor.adoc
> +image::photoresistor-CD.png[]
are you sure the circuit diagram is correct?  I am not sure it matches your description and you do not have  a wire connected to GPIO4. Also, the resistor on the south side of the board is connected to SPIMOSI pin and is not connect to the rest of the setup

2024-04-21 14:59 UTC, SwindleA commented on pi4micronaut-utils/src/docs/asciidoc/components/inputComponents/photoresistorSensor.adoc
> +    * Verify that the appropriate resistors are being used (220Ω)
for some reason, the bullet points in the troubleshooting section are not rendering properly. I think you need to remove the tab before them. 
![image](https://github.com/oss-slu/Pi4Micronaut/assets/60612512/714908d3-54ea-4708-b627-3727334d03aa)

2024-04-21 17:02 UTC, ruthvikm requested changes

2024-04-21 17:02 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/components/inputComponents/photoresistorSensor.adoc
> +
Add digital-output part of photo resistor.

2024-04-21 17:02 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/components/inputComponents/photoresistorSensor.adoc
> +===== Example
Example Controller

2024-04-22 21:58 UTC, SwindleA requested changes

2024-04-22 21:58 UTC, SwindleA commented on pi4micronaut-utils/src/docs/asciidoc/index.adoc
> +include::components/inputComponents/photoresistorSensor.adoc[]
remove the photosensor link in line 63, and delete the adoc file.

2024-04-22 22:04 UTC, ruthvikm requested changes
Circuit diagram need changes.

2024-04-23 01:41 UTC, SwindleA approved these changes
looks fabulous

2024-04-23 01:43 UTC, merged