Home automation bug fixes
oss-slu/Pi4Micronaut pull request #228
Opened 2024-04-15 21:29 UTC by jyanev

2024-04-18 19:34 UTC, SwindleA requested changes
one small issue. I am going to try to test with the setup tomorrow..

2024-04-18 19:34 UTC, SwindleA commented on src/main/java/com/example/pi4micronaut/HomeAutomation.java
>      private final PIRSensorHelper pirSensor;
For some reason my it does not build for me unless I comment out the rgb helper on line 31. Because it is not being used, remove the rgb helper.

2024-04-19 15:21 UTC, SwindleA requested changes
The big thing is that the way users are added needs to be fixed. The user should not be added to the list of authorized users until the fob has successfullly been written too. I consistently have the case that I cant write to the fob but the user is still added. Then when I try to deactivate the system, I get unathorized user.

2024-04-19 15:21 UTC, SwindleA commented on src/main/java/com/example/pi4micronaut/HomeAutomation.java
>      private final ActiveBuzzerHelper activeBuzzer;
buzzer still buzzes until the system is enabled, not sure if this is a bug or just how it works

2024-04-19 15:21 UTC, SwindleA commented on src/main/java/com/example/pi4micronaut/HomeAutomation.java
> +            this.users.add(userID);
only add the user to the array after the name is written to the card, if the rfid scanner times out, the user is added to the list but is not written to the fob.

2024-04-19 17:35 UTC, ruthvikm requested changes
Overall, the home automation functionalities are working as expected but need these changes to avoid confusion.
- [x] Need useful messages to be displayed on LCD along with Hello user. For example, if I scan a unauthorized tag, it should display a message "Unauthorized user".
- [x] Need to display a message on LCD when you turn on and off the system.
- [x] Clear the display while turning off the system with touch switch.
- [ ] For turning off the system using touch switch, user should scan a authorized tag. Now, it is considering the previous scanned tag as authorized user.

2024-04-19 18:03 UTC, ruthvikm commented on src/main/java/com/example/pi4micronaut/HomeAutomation.java
>      private final ActiveBuzzerHelper activeBuzzer;
I have fixed the circuit for the buzzer and pushed the changes.

2024-04-20 21:35 UTC, jyanev commented on src/main/java/com/example/pi4micronaut/HomeAutomation.java
> +            this.users.add(userID);
How do I know if the scanner times out or not? I don't see any functionality in the RFID Helper that tells me whether or not the name is written to the fob. For now, I just swapped lines 112 and 113 so that it writes to the fob before adding the user to the list. 
I think if we change the writeToCard() method to return a boolean for whether or not it successfully wrote to card, that one way I can think to fix this issue

2024-04-20 21:47 UTC, jyanev commented
> * [ ]  For turning off the system using touch switch, user should scan a authorized tag. Now, it is considering the previous scanned tag as authorized user.

I'm not sure if I understand what you mean by this. Is it using the scanned tag from when it adds a new user? or something else

2024-04-21 00:15 UTC, SwindleA commented on src/main/java/com/example/pi4micronaut/HomeAutomation.java
> +            this.users.add(userID);
I agree that the writeToCard should return a boolean, that would be a fix for this problem. I will create an issue for this.

2024-04-21 21:06 UTC, ruthvikm commented
> @ruthvikm
> 
> > * [ ]   For turning off the system using touch switch, user should scan a authorized tag. Now, it is considering the previous scanned tag as authorized user.
> 
> I'm not sure if I understand what you mean by this. Is it using the scanned tag from when it adds a new user? or something else

If the user wants to turn off the system using touch switch, it should let authorized user to scan the tag again before it disables the system.

2024-04-22 15:39 UTC, SwindleA approved these changes
I have tested and it works. For some reason the LCD screen backlight is off, not sure if that was intentional or not.

2024-04-22 16:48 UTC, ruthvikm requested changes

2024-04-22 16:48 UTC, ruthvikm commented on src/main/java/com/example/pi4micronaut/HomeAutomation.java
> +            log.info("!! USER ADDED !!");
Display this message on LCD

2024-04-22 16:48 UTC, ruthvikm commented on src/main/java/com/example/pi4micronaut/HomeAutomation.java
> +        log.info("!! USER REMOVED !!");
Display this message on LCD

2024-04-22 16:48 UTC, ruthvikm commented on src/main/java/com/example/pi4micronaut/HomeAutomation.java
> +                        log.info("!! AUTHORIZED USER: TURN OFF BUZZER !!");
Display this message on LCD.
first line: "Authorized User:"
second line: "Turning off Buzzer!"

2024-04-22 16:48 UTC, ruthvikm commented on src/main/java/com/example/pi4micronaut/HomeAutomation.java
> +                    log.info("!! PERSON DETECTED WITHIN 20 CM !!");
Display this message on LCD.

2024-04-22 16:49 UTC, ruthvikm requested changes

2024-04-22 16:49 UTC, ruthvikm commented on src/main/java/com/example/pi4micronaut/HomeAutomation.java
> +                        log.info("!! UNAUTHORIZED USER !!");
Display this message on LCD

2024-04-22 20:46 UTC, ruthvikm approved these changes
Look good

2024-04-22 20:47 UTC, merged