Fixes #230 | Servo Motor Documentation
oss-slu/Pi4Micronaut pull request #231
Opened 2024-04-26 17:34 UTC by adelgadoj3

Created the basis for the documentation. Need to fill in the remaining sections.

2024-04-29 19:33 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/components/outputComponents/servomotor.adoc
> +* Connect the 3.3V jumper wire to the power wire receiver (Color: Red)
mention this as VCC pin

2024-04-29 19:33 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/components/outputComponents/servomotor.adoc
> +* Connect the GPIO 18 jumper wire to the signal wire receiver (Color: Orange)
mention this as SIG pin

2024-04-29 19:34 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/components/outputComponents/servomotor.adoc
> +*Schematic Diagram*
i think we have Schematic diagram as a section

2024-04-29 19:50 UTC, ruthvikm commented on pi4micronaut-utils/src/docs/asciidoc/components/outputComponents/servomotor.adoc
> +This section provides details of the Servo Motor, including the components, and assembly instructions.
There are different types of servo motors. Specify which one we are providing support for. I think the one we are using is a "Micro Servo 9G - SG90" which is a positional servo with the range from 0 to 180 degrees

2024-04-29 19:51 UTC, ruthvikm requested changes
Requested few changes

2024-04-30 16:43 UTC, adelgadoj3 commented on pi4micronaut-utils/src/docs/asciidoc/components/outputComponents/servomotor.adoc
> +*Schematic Diagram*
In other components we have it as listed above *schematic diagram* . Would you like it to be its own own section? (i.e. ===== Schematic Diagram)

2024-05-01 21:01 UTC, ruthvikm approved these changes
Looks good to me.

2024-05-01 21:09 UTC, jyanev commented
nice (☞ﾟヮﾟ)☞
d=====(￣▽￣*)b

2024-05-01 21:11 UTC, merged