Fixed #246
oss-slu/Pi4Micronaut pull request #250
Opened 2024-09-16 02:48 UTC by tmacas

Handled Problem #246, awaiting code review.

2024-09-16 02:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/oss-slu/Pi4Micronaut?pullRequest=250) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/oss-slu/Pi4Micronaut?pullRequest=250) before we can accept your contribution.<br/><hr/>**Thomas Macas** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/oss-slu/Pi4Micronaut?pullRequest=250) it.</sub>

2024-09-16 22:19 UTC, leandrumartin reviewed
Looks good. I like the descriptiveness of the error messages.

2024-09-16 22:19 UTC, leandrumartin commented on components/src/main/java/com/opensourcewithslu/components/controllers/PushButtonController.java
Added comments to changed lines are unnecessary

2024-09-16 22:19 UTC, leandrumartin commented on components/src/main/java/com/opensourcewithslu/components/controllers/LEDController.java
> +import org.slf4j.LoggerFactory;
duplicate import

2024-09-18 14:50 UTC, yrlmanoharreddy commented on components/src/main/java/com/opensourcewithslu/components/controllers/LEDController.java
> +import org.slf4j.LoggerFactory;
Ensure that unnecessary spaces in the import statements are removed to adhere to standard code formatting practices.For example, on line 4, there is an extra space that should be corrected

And you used same imports twice that means it is adding redundacy to the code. Avoid redundancy by removing duplicate import statements

2024-09-18 23:51 UTC, yrlmanoharreddy commented on components/src/main/java/com/opensourcewithslu/components/controllers/MicroSwitchController.java
There is an extra space between two data members(between 16th and 17th line) that should be removed for code consistency

2024-09-18 23:54 UTC, yrlmanoharreddy commented on components/src/main/java/com/opensourcewithslu/components/controllers/PhotoResistorController.java
There is an extra space got added after imports. Remove those spaces to enhance code quality

2024-09-18 23:58 UTC, yrlmanoharreddy commented on components/src/main/java/com/opensourcewithslu/components/controllers/PushButtonController.java
Address the space that got added between data members(between 16 and 18th line). Removing spaces will improve overall code quality

2024-09-19 00:02 UTC, yrlmanoharreddy commented on components/src/main/java/com/opensourcewithslu/components/controllers/TouchSwitchController.java
The fix addresses the error handling with LED status indication and aligns with feature requirements. Extra whitespace should be cleaned up, and the logging could be refined for clarity. Functionally, the code works well. Great job on handling errors—just focus on minor cleanup to improve maintainability. Appreciate the effort!

2024-09-19 00:04 UTC, yrlmanoharreddy commented
The fix effectively handles the error management with LED status indication and meets the feature requirements. However, there are some minor issues, including extra whitespace and duplicate imports, that need to be addressed for better code quality. Additionally, refining the logging for clarity would be helpful. Please make these changes and push the updated code. Great work so far—looking forward to the revisions!

2024-09-20 16:31 UTC, tmacas commented
Fixes #246 
Completed round of solution to comments from code review. Removed unnecessary white spaces and import repeats for code clarity and quality.

2024-09-21 02:11 UTC, yrlmanoharreddy requested changes
The fix effectively handles the error management with LED status indication and meets the feature requirements. However, there are some minor issues, including extra whitespace and duplicate imports, that need to be addressed for better code quality. Additionally, refining the logging for clarity would be helpful. Please make these changes and push the updated code. Great work so far—looking forward to the revisions!

2024-09-22 20:25 UTC, closed without merging

2024-09-22 20:32 UTC, yrlmanoharreddy commented
Closing the existing pull request and opening a new pull request to address the unresolved CLA issue. This will give the CLA assistant a fresh start to track the commit properly.

New pull request url:
https://github.com/oss-slu/Pi4Micronaut/pull/253