249 push button helper tests
oss-slu/Pi4Micronaut pull request #251
Opened 2024-09-16 19:03 UTC by Ed0827

Fixes #249 

Updated the gradle build for JUnit.

Added unit tests for PushButtonHelper initialization.

This issue was needed to change because it involves setting up and verifying fundamental functionality, which makes it suitable for newcomers.

Created an instance of the class named MOckDigitalInput to simulates the behavior of a real object in controlled ways, without needing the real hardware or dependencies. Hence, it mimics the behavior of a real digital input device, such as a push button connected to a Raspberry Pi's GPIO pins. Tested the case isPressed to simulate different conditions like the button being pressed or not by setting specific states that created: DigitalState.LOW or DigitalState.HIGH.

2024-09-16 19:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/oss-slu/Pi4Micronaut?pullRequest=251) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/oss-slu/Pi4Micronaut?pullRequest=251) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/oss-slu/Pi4Micronaut?pullRequest=251) it.</sub>

2024-09-16 22:09 UTC, tmacas commented on pi4micronaut-utils/src/docs/javadoc/legal/COPYRIGHT
> +Copyright � 1993, 2018, Oracle and/or its affiliates.
Was this intentionally added, or was this just a dependability?

2024-09-16 22:19 UTC, tmacas commented on pi4micronaut-utils/src/test/java/com/opensourcewithslu/inputdevices/PushButtonHelperTests.java
> +        MockDigitalInput input = new MockDigitalInput();
Add a comment for each function explain its intended goal. However try to avoid over commenting

2024-09-16 22:20 UTC, tmacas commented on pi4micronaut-utils/src/test/java/com/opensourcewithslu/inputdevices/MockDigitalInput.java
> +public class MockDigitalInput implements DigitalInput {
Very long class, Could possibly separate into multiple classes.

2024-09-19 01:23 UTC, yrlmanoharreddy commented on pi4micronaut-utils/src/test/java/com/opensourcewithslu/inputdevices/MockDigitalInput.java
> +public class MockDigitalInput implements DigitalInput {
Please do remove the unnecessary code in the MockDigitalInput.

2024-09-19 01:28 UTC, yrlmanoharreddy commented
Your implementation of the MockDigitalInput class effectively simulates the behavior of digital input devices, which is crucial for testing without real hardware. However, there are some areas for improvement.

For better code quality, remove unused code from the MockDigitalInput class to maintain clarity and prevent confusion. The approach is solid. Great work so far—looking forward to the revisions!

Please make these changes and push the updated code

2024-09-21 02:08 UTC, yrlmanoharreddy requested changes
Your implementation of the MockDigitalInput class effectively simulates the behavior of digital input devices, which is crucial for testing without real hardware. However, there are some areas for improvement.

For better code quality, remove unused code from the MockDigitalInput class to maintain clarity and prevent confusion. The approach is solid. Great work so far—looking forward to the revisions!




The task tasks you need to complete:
1. Remove unused code from the MockDigitalInput class.
2. Adding concise comments to each function to clarify its intended
3. Lastly, please use different folder for MockDigitalInput class. Like pi4micronaut-utils/src/test/java/com/opensourcewithslu/mock/MockDigitalInput.java


Please make these changes and push the updated code

2024-09-21 02:08 UTC, yrlmanoharreddy commented on pi4micronaut-utils/src/test/java/com/opensourcewithslu/inputdevices/PushButtonHelperTests.java
> +        MockDigitalInput input = new MockDigitalInput();
The code overall looks solid, but I recommend adding concise comments to each function to clarify its intended goal. This will improve readability and help future contributors quickly understand the purpose of each method without over-explaining. Avoid over-commenting or restating obvious logic; focus on the "why" behind the function rather than the "how."

2024-09-22 21:54 UTC, yrlmanoharreddy approved these changes
Great Work and wrote first unit tests for the Push button class. Resolved #251

2024-09-22 23:02 UTC, merged