Issue #247: Added unit tests for LEDHelper functions
oss-slu/Pi4Micronaut pull request #252
Opened 2024-09-16 21:04 UTC by leandrumartin

Fixes #247. Added JUnit and Mockito dependencies in in the `pi4micronaut-utils` folder. Added unit tests for `LEDHelper` class functions in basic states, mocking the output class as required in issue description. All the tests pass.

The issue description adds that the tests should check whether the `LEDHelper` generates appropriate log messages, but this is not yet taken care of.

2024-09-16 22:22 UTC, Ed0827 reviewed
It looks great! All the unit tests for the LEDHelper class functions work as intended, and the conditional statements are descriptive and easy to follow.

2024-09-19 00:22 UTC, yrlmanoharreddy commented on pi4micronaut-utils/src/test/java/com/opensourcewithslu/Pi4MicronautUtilsTest.java
The tests address key functionality but don't follow the modular structure we discussed, which is crucial for consistency and maintainability. From a product perspective, aligning the tests with the project's design ensures future scalability. The tests cover important scenarios, but they need to follow the same structure as the main code. Please revise accordingly to improve clarity and maintainability. Great effort—looking forward to the updated tests!

2024-09-19 00:28 UTC, yrlmanoharreddy commented
The tests address key functionality but don't follow the modular structure we discussed, which is crucial for consistency and maintainability. From a product perspective, aligning the tests with the project's design ensures future scalability. The tests cover important scenarios, but they need to follow the same structure as the main code. Please revise accordingly to improve clarity and maintainability. Great effort—looking forward to the updated tests!

**TASK:**
**Changes that need to be done:**

"Follow the structure same as the main code's structure."

Example in your case:

* Actual main code structure:
pi4micronaut-utils/src/main/java/com/opensourcewithslu/outputdevices/LEDHelper.java
* Expected Structure for unit test should be
pi4micronaut-utils/src/test/java/com/opensourcewithslu/outputdevices/LEDHelperTest.java

2024-09-21 02:09 UTC, yrlmanoharreddy requested changes
The tests address key functionality but don't follow the modular structure we discussed, which is crucial for consistency and maintainability. From a product perspective, aligning the tests with the project's design ensures future scalability. The tests cover important scenarios, but they need to follow the same structure as the main code. Please revise accordingly to improve clarity and maintainability. Great effort—looking forward to the updated tests!

TASK:
Changes that need to be done:

"Follow the structure same as the main code's structure."

Example in your case:

Actual main code structure:
pi4micronaut-utils/src/main/java/com/opensourcewithslu/outputdevices/LEDHelper.java
Expected Structure for unit test should be
pi4micronaut-utils/src/test/java/com/opensourcewithslu/outputdevices/LEDHelperTest.java
Additionally, please use "camelCase" conventions for member functions.

2024-09-21 02:14 UTC, yrlmanoharreddy requested changes
The tests address key functionality but don't follow the modular structure we discussed, which is crucial for consistency and maintainability. From a product perspective, aligning the tests with the project's design ensures future scalability. The tests cover important scenarios, but they need to follow the same structure as the main code. Please revise accordingly to improve clarity and maintainability. Great effort—looking forward to the updated tests!

TASK:
Changes that need to be done:

"Follow the structure same as the main code's structure."

Example in your case:

Actual main code structure:
pi4micronaut-utils/src/main/java/com/opensourcewithslu/outputdevices/LEDHelper.java
Expected Structure for unit test should be
pi4micronaut-utils/src/test/java/com/opensourcewithslu/outputdevices/LEDHelperTest.java
Additionally, please use "camelCase" conventions for member functions.

2024-09-22 04:46 UTC, yrlmanoharreddy requested changes
The test cases are functional but currently don’t adhere to the modular structure we discussed, which is essential for maintaining consistency and ensuring long-term scalability. From a product standpoint, aligning the test structure with the main codebase will make future expansion and maintenance smoother. While the tests cover critical scenarios, they need to be organized to reflect the structure of the main code.

Required changes:

1. Follow the same structure as the main code:
    Here’s an example:
    
    **Current structure:** pi4micronaut-utils/src/main/java/com/opensourcewithslu/LEDHelper.java
    **Main code structure**: pi4micronaut-utils/src/main/java/com/opensourcewithslu/outputdevices/LEDHelper.java
    **Expected structure for the unit test**: pi4micronaut-utils/src/test/java/com/opensourcewithslu/outputdevices/LEDHelperTest.java
    Please ensure your tests follow the same structure as the main codebase.

2. Two of your test cases are failing:
ledOnLogsWhenTurnedOn()
ledOffLogsWhenTurnedOff()
Kindly fix these issues before pushing the changes back

2024-09-22 15:45 UTC, leandrumartin commented
I believe I've made all the necessary changes now.

2024-09-22 23:22 UTC, yrlmanoharreddy approved these changes
Done the changes according to the review and resolved issue #252 and also resolved merge conflicts in this commit

2024-09-22 23:22 UTC, merged