JOSS Paper submission
oss-slu/Pi4Micronaut pull request #256
Opened 2024-09-24 01:01 UTC by ruthvikm

- Final Draft version of the JOSS paper. 
- Created workflow to build the draft paper pdf
- [paper.pdf](https://github.com/user-attachments/files/17106411/paper.pdf)

2024-10-05 21:21 UTC, kungfuchicken requested changes
i think it's basically ready to ship.

2024-10-05 21:21 UTC, kungfuchicken commented on joss-paper/paper.md
> +This allows researchers to use Java, a well-established programming language in scientific computing, to interact with hardware components on the Raspberry Pi,
"`Java, a well-established programming language in scientific computing,`" citations supporting this claim would be good (https://doi.org/10.1002/cae.20217 etc.)

2024-11-14 15:41 UTC, kate-holdener approved these changes
Looks good to me! Feel free to merge and submit to JOSS.

2024-12-06 21:50 UTC, kungfuchicken approved these changes
lgtm;

2024-12-06 21:50 UTC, merged