45 Fan Support Helper Tests
oss-slu/Pi4Micronaut pull request #259
Opened 2024-09-30 03:53 UTC by Ed0827

Fixes #45

Updated the Gradle build configuration to include support for Pi4J Micronaut. Added the fan control feature with support for turning on, turning off, and setting the fan speed using PWM.

Created FanController.java to provide HTTP endpoints for fan control and FanHelper.java to handle the logic for fan operations, including starting, stopping, and adjusting speed.

Implemented methods: start() to start the fan at full speed, stop() to stop the fan, and setSpeed(int speed) to set the fan speed using PWM with a value range of 0 to 1024.

2024-09-30 17:58 UTC, yrlmanoharreddy requested changes
1) Delete the FanController that was defined under the inputdevices
2) Delete the Pi4J cofiguration from the yml file 
3) Change the class name for FanHelper under unittests
4) Please change the class name in FanHelper.java same as file name, followed by constructor too.

2024-09-30 21:56 UTC, ThomasMacas commented on pi4micronaut-utils/src/main/java/com/opensourcewithslu/outputdevices/FanHelper.java
> +
Looks great, although this white space could do to be deleted as many of the other __Helper.java files have the final variable without whitespace after the function.

2024-10-01 13:50 UTC, kate-holdener commented on pi4micronaut-utils/src/main/resources/application.yml
What's this change for?

2024-10-01 13:56 UTC, kate-holdener commented
Looks like FanController is missing (probably should be there under outputdevices?) The yml configuration for a fan is also missing.

2024-10-06 13:35 UTC, yrlmanoharreddy approved these changes
Added FanHelper.java class to manage fan initialization and speed control using the Pi4J library. Implemented methods to start, stop, and adjust the fan speed, along with an example controller demonstrating how to use FanHelper.java. Integrated GPIO pin configuration via YAML for seamless setup.

2024-10-06 13:35 UTC, merged