DC Motor documentation
oss-slu/Pi4Micronaut pull request #268
Opened 2024-10-11 16:32 UTC by leandrumartin

Added motor.adoc file. Currently it includes info about API calls, YAML file, and a link to the example controller.

2024-10-14 12:16 UTC, yrlmanoharreddy commented on pi4micronaut-utils/src/docs/asciidoc/components/outputComponents/motor.adoc
Remove "TODO: finish documentation here" under the Assembly Instructions.

2024-10-14 12:16 UTC, yrlmanoharreddy requested changes
The implementation aligns well with the project requirements, but please remove the "TODO: finish documentation here" note under the Assembly Instructions. From a product and code quality perspective, it's important to keep the code clean and avoid placeholder comments. Looking forward to the updates.

Todo:
Remove "TODO: finish documentation here" under the Assembly Instructions.

2024-10-14 22:26 UTC, ThomasMacas commented on pi4micronaut-utils/src/docs/asciidoc/components/outputComponents/motor.adoc
> +* `/disable` - Disables the motor.
Show how these could be run from command line.

2024-10-21 00:53 UTC, yrlmanoharreddy approved these changes
This pull request successfully implements the DC motor control functionality, providing comprehensive documentation that includes component descriptions, YAML configuration, circuit setup images, and clear usage instructions. The detailed information will greatly assist users in controlling motor speed and direction effectively.
Resolved #263

2024-10-21 00:53 UTC, merged