Thermistor Support
oss-slu/Pi4Micronaut pull request #273
Opened 2024-10-28 19:06 UTC by ThomasMacas

Fixes #39 

In order to integrate a thermistor as another component a Controller and Helper files are needed. In order for the Raspberry pi to integrate with our software the Application.yml file was adjusted to accommodate for the thermistor. The ThermistorHelper.java file was create to give the basic operations for the thermistor and the ThermistorController.java as a basic implementation of it.

2024-10-28 22:40 UTC, leandrumartin requested changes

2024-10-28 22:40 UTC, leandrumartin commented on components/src/main/resources/application.yml
Should there be a `thermistor-output` under `digital-output`? It looks like the controller takes one in as a constructor parameter.

2024-10-28 22:40 UTC, leandrumartin commented on components/src/main/java/com/opensourcewithslu/components/controllers/ThermistorController.java
> +    public ThermistorController(@Named("thermistor-input") DigitalInput sensorInput, @Named("thermistor-output") DigitalOutput sensorOutput){
If the only endpoint is to read a value, do we need a DigitalOutput here? Or are there more endpoints planned that involve using the thermistor as an output for something?

2024-10-30 23:26 UTC, yrlmanoharreddy requested changes
There is the actual functionality to be implemented in the helper class. Please ensure all planned features are fully developed and tested with actual hardware to confirm correct communication protocols. Once everything is finalized, we’ll be ready for a thorough review.

2024-11-05 03:51 UTC, yrlmanoharreddy approved these changes
This pull request implements support for the thermistor component; however, we currently lack the necessary Analog-to-Digital Converter (ADC) to test the hardware functionality effectively. To ensure thorough testing, I plan to prioritize ADC support in the next sprint and test the thermistor hardware in parallel.

2024-11-05 03:52 UTC, merged