Add documentation for 4-digit 7-segment display
oss-slu/Pi4Micronaut pull request #282
Opened 2024-11-11 21:39 UTC by leandrumartin

Resolves #277. 

The documentation for the 4-digit 7-segment display component was added in `fourDigitSevenSegment.adoc` along with appropriate diagrams. The documentation describes necssary components, assembly instructions, functionality, how to test it, and troubleshooting.

The functionality description specifies what values are allowed as input to the display. The assembly instructions are partially stubbed out for now.

The changes here also include changes merged from the branch adding the 4-digit 7-segment display, `pi4micronaut-44`. These changes are to `FourDigitSevenSegmentDisplayController.java`, `application.yml`,  `FourDigitSevenSegmentDisplayHelper.java`, and `FourDigitSevenSegmentDisplayHelperTest.java`.

2024-11-11 23:22 UTC, ThomasMacas commented on pi4micronaut-utils/src/docs/asciidoc/components/outputComponents/fourDigitSevenSegment.adoc
> +- Digit 1 to GPIO17 (BCM pin 18)
Make sure that when the new version of the code is submitted that the appropriate wiring configuration changes changes according to it.

2024-11-11 23:22 UTC, ThomasMacas commented on pi4micronaut-utils/src/docs/asciidoc/components/outputComponents/fourDigitSevenSegment.adoc
> +i2c:
Make sure to change your config if that changes based on the new updates to the controller later.

2024-11-11 23:22 UTC, ThomasMacas commented on pi4micronaut-utils/src/docs/asciidoc/components/outputComponents/fourDigitSevenSegment.adoc
> +$ curl http://localhost:8080/four-digit-seven-segment/enable
For ease of use and documentation maybe create a curl for each function reference, such as adding 

curl http://localhost:8080/four-digit-segment/clear

to show it without question.

2024-11-12 22:43 UTC, yrlmanoharreddy requested changes
Your pull request includes helper functionality, controller, and YAML configuration changes that were already pushed in the previous sprint. Since that pull request is still pending, you should push updates into the existing one instead. This current pull request should only contain files modified under the docs section. Please remove all unrelated files to keep the changes focused and maintain a clean commit history

2024-11-15 02:23 UTC, closed without merging

2024-11-18 22:19 UTC, Ed0827 reviewed
I made a review on Nov 11, but I accidentally did not subming review.

2024-11-18 22:19 UTC, Ed0827 commented on components/src/main/java/com/opensourcewithslu/components/controllers/FourDigitSevenSegmentDisplayController.java
> +//tag::ex[]
is adding this tag to use in documentation?