41 seven segement display documentation
oss-slu/Pi4Micronaut pull request #284
Opened 2024-11-11 23:17 UTC by Ed0827

Overview: Introduction to the Seven Segment Display component and its purpose.
Components: List of required hardware components.
Circuit Setup: Step-by-step guide for setting up the display on a breadboard.
Circuit and Schematic Diagrams: Visual references for wiring.
YAML Configuration: Detailed YAML setup for integrating the display with Raspberry Pi via I2C.
Functionality and Testing: Instructions for displaying numbers and controlling segments.
Troubleshooting: Common issues and solutions.

2024-11-11 23:32 UTC, leandrumartin commented on pi4micronaut-utils/src/docs/asciidoc/components/outputComponents/SevenSegementDisplay.adoc
> +* Power source
Some of the other documentation files mention the amount of power needed by the power source. It could be helpful to add it here.

2024-11-11 23:32 UTC, leandrumartin commented on pi4micronaut-utils/src/docs/asciidoc/components/outputComponents/SevenSegementDisplay.adoc
> +2. Connect each segment of the display to its respective GPIO pin as specified in the YAML configuration.
Maybe this should be more detailed and describe where the wiring should go.

2024-11-11 23:32 UTC, leandrumartin commented on pi4micronaut-utils/src/docs/asciidoc/components/outputComponents/SevenSegementDisplay.adoc
> +image::/Users/jeongseyun7/Desktop/Capston1/Sprint4/Refreshed/Pi4Micronaut/Circuit_Diagram.png[]
This should be a relative file path, not a local one. This won't show up on any computer but yours!

Instead, this line should look like:

`image::Circuit_Diagram.png[]`

The image should be placed inside `pi4micronaut-utils/src/docs/asciidoc/img`. It looks like the images aren't added and committed yet, so be sure to do that as well.

2024-11-11 23:32 UTC, leandrumartin commented on pi4micronaut-utils/src/docs/asciidoc/components/outputComponents/SevenSegementDisplay.adoc
> +4. Refer to the circuit diagram for detailed wiring instructions.
I do like this reminder to refer to the circuit diagram!

2024-11-11 23:32 UTC, leandrumartin commented on pi4micronaut-utils/src/docs/asciidoc/components/outputComponents/SevenSegementDisplay.adoc
> +package com.opensourcewithslu.components.controllers;
The code here should be linked to the `SevenSegmentController.java` file instead of being hardcoded and rewritten here.

2024-11-12 22:41 UTC, yrlmanoharreddy requested changes
Your pull request includes helper functionality, controller, and YAML configuration changes that were already pushed in the previous sprint. Since that pull request is still pending, you should push updates into the existing one instead. This current pull request should only contain files modified under the docs section. Please remove all unrelated files to keep the changes focused and maintain a clean commit history

2024-12-04 01:56 UTC, closed without merging