Adding LICENSE
oss-slu/Pi4Micronaut pull request #51
Opened 2023-04-27 22:39 UTC by GreihMurray

Added apache 2.0 license to project

2023-04-28 15:24 UTC, traison-diedrich requested changes
Line 189 Should be filled out in License

2023-04-28 15:33 UTC, GreihMurray commented
> Line 189 Should be filled out in License

Thanks for catching that, I didn't actually read all the way through it t be honest.

2023-04-28 15:35 UTC, traison-diedrich approved these changes

2023-05-06 20:03 UTC, liusinuo2000 approved these changes

2023-05-06 20:05 UTC, merged