Multi pin docs
oss-slu/Pi4Micronaut pull request #53
Opened 2023-05-15 15:56 UTC by GreihMurray

2023-05-15 16:24 UTC, traison-diedrich approved these changes

2023-10-09 22:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/oss-slu/Pi4Micronaut?pullRequest=53) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/oss-slu/Pi4Micronaut?pullRequest=53) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/oss-slu/Pi4Micronaut?pullRequest=53) it.</sub>

2023-10-16 19:24 UTC, SwindleA requested changes
Because so many changes have been made to the current documentation, I recommend that the document changes not be merged. We can save the information that needs to be added and add it through a different issue.

2024-01-04 18:11 UTC, ruthvikm commented
Create a new issue to add these changes if necessary

2024-01-04 18:11 UTC, closed without merging