Issue 54 - Added Contributor License Agreement
oss-slu/Pi4Micronaut pull request #70
Opened 2023-09-25 20:06 UTC by jyanev

Based on Micronaut's. Still need to implement using cla assistant

2023-09-26 16:28 UTC, ruthvikm approved these changes

2023-09-26 17:20 UTC, kate-holdener submitted a review, later dismissed
I think this PR doesn't fully resolve issue #54 . In the description of the issue, I see that "Completion of this issue also includes directions on how to fill out the CLA in the "Contributing to the Library" section of the docs". This part is missing. Also, when looking at Micronaut's CLA on their website, I am able to digitally sign the CLA. The solution provided in this PR is just the wording of the CLA, but other connecting pieces are missing.

2023-09-28 19:21 UTC, ruthvikm requested changes
Use [https://cla-assistant.io/]Cla assistant website to configure CLA for Pi4Micronaut. You can update the documentation a bit more precise about Pi4Micronaut and paste the cla documentation which you have used in the CLA.md file while congifuration.

2023-10-10 00:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/oss-slu/Pi4Micronaut?pullRequest=70) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/oss-slu/Pi4Micronaut?pullRequest=70) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: jyanev<br/>:x: ruthvikm<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/oss-slu/Pi4Micronaut?pullRequest=70) it.</sub>

2023-10-10 00:33 UTC, SwindleA commented
@ruthvikm  The table of contents is missing. I was able to re-add it but the resulting format is a bit janky. 


![image](https://github.com/oss-slu/Pi4Micronaut/assets/60612512/4353b54a-7b63-4687-a7ed-f026321a461a)

When you scroll down, the png disappears to the top. 

![image](https://github.com/oss-slu/Pi4Micronaut/assets/60612512/6bb0cf6c-5cec-4f0c-9bef-ff5b09623732)



The code to add it back:
```
= Pi4Micronaut Documentation
:source-highlighter: rouge
:rouge-style: thankful_eyes
:stylesheet: style.css
:docinfo: shared
:icons: font
:doctype: book
:notitle:
:toc: left
:toclevels: 3
:sectanchors:
:sectnums:

image::../../../../Pi4Micronaut_logo.png[]

toc::[]
```
This is the first 16 lines. I did not commit any changes, because I am not sure what layout you want.

2023-11-01 17:45 UTC, ruthvikm approved these changes
Made necessary changes

2023-11-01 20:37 UTC, SwindleA requested changes

2023-11-01 20:37 UTC, SwindleA commented on micronautpi4j-utils/src/docs/asciidoc/contributingToLibrary.adoc
> +== Contribute to the Pi4Micronaut Library
Duplicate file

2023-11-01 20:37 UTC, SwindleA commented on micronautpi4j-utils/src/docs/asciidoc/contribute/newComponent.adoc
> -=== How to Create a New Component
Readd equal sign to make this a subsection of contributing to library

2023-11-01 20:37 UTC, SwindleA commented on micronautpi4j-utils/src/docs/asciidoc/contribute/contributingToLibrary.adoc
> +include::newComponent.adoc[]
Move this to index.adoc

2023-11-01 20:48 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/contributingToLibrary.adoc
> +== Contribute to the Pi4Micronaut Library
deleted

2023-11-01 20:48 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/contribute/newComponent.adoc
> -=== How to Create a New Component
made changes

2023-11-01 20:49 UTC, ruthvikm commented on micronautpi4j-utils/src/docs/asciidoc/contribute/contributingToLibrary.adoc
> +include::newComponent.adoc[]
moved it to index.adoc

2023-11-02 21:34 UTC, SwindleA approved these changes
Looks good

2023-11-02 21:55 UTC, merged