began implementation of light sensor controller and helper
oss-slu/Pi4Micronaut pull request #88
Opened 2023-10-16 19:10 UTC by jyanev

added constructor for light sensor controller and helper

2023-10-24 20:26 UTC, SwindleA commented on micronautpi4j-utils/src/main/java/com/opensourcewithslu/inputdevices/LightSensorHelper.java
> +                             @Named("photo-resistor-input") DigitalInput sensorInput,
In other components, the @Named things are set in the Controller.

2023-10-24 20:28 UTC, SwindleA commented on micronautpi4j-utils/src/main/java/com/opensourcewithslu/inputdevices/LightSensorHelper.java
> +        this.ledHelper = ledHelper;
The helper should only interact with the light sensor.  Interactions with the led should be taken care of in the controller.

2023-10-24 20:36 UTC, SwindleA requested changes
There are several things that should be moved from the helper to the controller.  I think it should be discussed what should be done with `Darkness.java`. Do we try and move the darkness code into the helper, to minimize the number of files, or do we establishes how to store the helper files to a helper?

2023-10-24 20:36 UTC, SwindleA commented on micronautpi4j-utils/src/main/java/com/opensourcewithslu/inputdevices/LightSensorHelper.java
> +    private void initializePhotoSensor() {
I think this should be moved to the controller.

2023-10-24 20:36 UTC, SwindleA commented on micronautpi4j-utils/src/main/java/com/opensourcewithslu/inputdevices/LightSensorHelper.java
> +                             @Named("photo-resistor-input") DigitalInput sensorInput,
In other components, the `@Named` things are set in the Controller.

2023-10-24 20:36 UTC, SwindleA commented on micronautpi4j-utils/src/main/java/com/opensourcewithslu/inputdevices/LightSensorHelper.java
> +        this.ledHelper = ledHelper;
The helper should only interact with the light sensor. Interactions with the led should be taken care of in the controller.

2023-10-24 21:54 UTC, ruthvikm requested changes
Test your code on raspberry pi and share the results. If it is working, then we can merge this component's code to main

2023-10-24 21:54 UTC, ruthvikm commented on micronautpi4j-utils/src/main/java/com/opensourcewithslu/inputdevices/Darkness.java
We use only one helper class to provide support for a component. Please make necessary corrections and merge the content of this file to LightSensorHelper.java.

2023-10-24 21:54 UTC, ruthvikm commented on micronautpi4j-utils/src/main/java/com/opensourcewithslu/inputdevices/LightSensorHelper.java
> +                             @Named("photo-resistor-input") DigitalInput sensorInput,
I agree with Adrian

2023-12-26 03:12 UTC, ruthvikm commented
working on a new branch

2023-12-26 03:12 UTC, closed without merging